version: "2"
services:

  # AWS OTel Collector
  aws-ot-collector:
#    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    # very slow when you build it first time locally!!!
    build:
     context: ../
     dockerfile: cmd/awscollector/Dockerfile
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG"]
    environment:
      - AWS_REGION=us-west-2

      # Either uncomment and define these:
      #
      # - AWS_PROFILE=<profile>
      # - AWS_ACCESS_KEY_ID=<to_be_added>
      # - AWS_SECRET_ACCESS_KEY=<to_be_added>
      #
      # Or define a profile available in your shared credentials file
      #
      # - AWS_PROFILE=myprofile

    volumes:
      - ../examples/config-test.yaml:/etc/otel-agent-config.yaml
      - ~/.aws:/root/.aws
    ports:
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
  ot-metric-emitter:
    privileged: true
    image: aottestbed/aws-otel-load-generator:v0.1.3
    command: [ "trace", "-r=5000", "-u=aws-ot-collector:9411", "-d=zipkin" ]
    environment:
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=aws-otel,service.name=aws-otel-integ-test
      AWS_REGION: us-west-2
