name: noop-one-name

on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.TEST_ROLE_ARN }}
          aws-region: us-west-2

      - run: echo winner
        name: done